### ISSUE TITLE
Hey Rokma

### ISSUE THREAD

**Issue by agustinustheo** [toybreaker/rokma#20]
Hey Rokma,

This is Theo, we met a few days ago.

How are you? I hope you are doing well.

Best regards,
Theo

**Comment by agustinustheo** [comment]
I couldn't find your contacts @toybreaker

**Comment by toybreaker** [comment]
COOL!
You made it thru… eh eh

**Comment by toybreaker** [comment]
dude, i checked your github profile and wow... you coding some serious stuff, compliments!!!

**Comment by agustinustheo** [comment]
Thanks @toybreaker I appreciate it.

**Comment by agustinustheo** [comment]
Before I close this since I found your socials already maybe we should continue chatting in private hehe.

**Comment by toybreaker** [comment]
> On 8 Mar 2022, at 14.31, Agustinus Theodorus ***@***.***> wrote:
> 
> 
> I couldn't find your contacts @toybreaker <https://github.com/toybreaker>
> 


Really?
In my profile there my website with in the contact got all my email social etc…

Also junglestarg.org <http://junglestarg.org/> at page bottom got the mail contact
...
